### ISSUE TITLE
How can I write the dictionary without key in snappyHexMeshDict？

### ISSUE THREAD

**Issue by zzkluck** [gerlero/foamlib#293]
I am trying to generate a `snappyHexMeshDict` and encountering such an example. The whole `snappyHexMeshDict` I want is like:
```
.....
castellatedMeshControls
{
    ......
    features
    (
        {
            file        "cylinder.eMesh";
            levels       ((0.5 4));
        }
    );
    ......
}
......
```
That's `a list of dictionary without keys`. It seems that openfoam uses a very different syntax here than it does elsewhere.  My intuition is that will work:
```python
snappy_dict["castellatedMeshControls"] = {
    ......
    "features": [{
        "file": "cylinder.eMesh",
        "levels":  "((0.5 4))";
    }],
    ......
}
```
But this will output:
```
features 
(
    file "cylinder.eMesh"; 
    levels ((0.5 4));
);
```
I tried several other methods, but found it difficult. What I can do here?

**Comment by gerlero** [comment]
@zzkluck Thanks for the report. I hadn't considered this case, so indeed I don't think there's a way to read/write something like this now. I'll try to get a fix out as soon as possible.

**Comment by gerlero** [comment]
@zzkluck Thanks again. Version 0.8.0 is now out and should fix this. Feel free to reopen otherwise.

**Comment by gerlero** [comment]
Actually, 0.8.0 is not yet published on PyPI because the release workflow bumps into a setuptools bug (https://github.com/pypa/setuptools/issues/4759). Sorry about that. I'll keep trying to publish it

**Comment by zzkluck** [comment]
> 0.8.0 is now out

Thank you for such a quick update, now my code can work well!
