### ISSUE TITLE
[Bug Report] Complex scheme is incorrectly identified as List in fvSchemes

### ISSUE THREAD

**Issue by zzkluck** [gerlero/foamlib#309]
Some expressions in `divSchemes` are complicated, for example:
```
divSchemes
{
    default         bounded Gauss upwind;

    div((nuEff*dev(T(grad(U))))) Gauss linear;
}
```
`foamlib` crashes when it reads the `fvSchemes` file containing such items. Writing similar items will also crash, but there is an inelegant plan B:
```python
foam_file = FoamFile('/path/to/fvSolution')
foam_file['div(nuEff*dev(T(grad(U))))'] = "Hello world"  # will crash
foam_file['"div(nuEff*dev(T(grad(U))))"'] = "Hello world" # Success
```

After some debugging, I found `_parsing.parse_data()` dramatically recognized it as a list, like:
```
('div', ['nuEff*dev', ['T', ['grad(U)']]])
```
I was surprised to find that this lengthy equation term expressions really conforms to the openfoam LIST syntax. But that's clearly not what we want.

**Comment by gerlero** [comment]
@zzkluck Thanks. I'll take a look at it!
